version: "3.9"

services:
  node_app:
    container_name: node_app
    image: lalman/videos-node-app
    ports:
      - "4000:4000"
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: mongodb:12
    ports:
      - "5432:5432"

volumes:
  node_db_data: {}


